version: "3"
services:
  web:
    build: web/
    image: ${PROJECT_PREFIX}-web
    container_name: ${PROJECT_PREFIX}-web
    volumes:
      - ./web/app:/var/www/html
    environment:
      DB_HOST: db
      DB_DATABASE: ${MYSQL_DATABASE}
      DB_USERNAME: ${MYSQL_USER}
      DB_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - 80:80
    links:
      - db

  db:
    image: mysql:5.7
    container_name: ${PROJECT_PREFIX}-db
    restart: always
    volumes:
      - ./mysql/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}